name: API Tests - DogAPI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Realiza o checkout do projeto
        uses: actions/checkout@v4

      - name: Instalação do JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Download das dependências do Maven
        run: mvn dependency:go-offline -B

      - name: Execução dos testes API
        run: mvn clean test -Dcucumber.filter.tags="@regressao"

      - name: Publicar relatório Cucumber
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatório-do-teste
          path: |
            target/cucumber-reports